name: Test driftctl-action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
    - name: Approve
      run: echo For security reasons, all pull requests need to be approved first

  test:
    runs-on: ubuntu-latest
    needs: [approve]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run driftctl
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          DCTL_NO_VERSION_CHECK: true
          DCTL_FROM: "tfstate://tests/terraform.tfstate"
          DCTL_DRIFTIGNORE: "tests/.driftignore"
          DCTL_FILTER: "Type=='unknown_type'" # Makes driftctl to exit 0 each time

  test-matrix:
    runs-on: ubuntu-latest
    needs: [approve]
    strategy:
      matrix:
        version: [0.5.0, 0.9.0, 0.10.0, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run driftctl
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          DCTL_NO_VERSION_CHECK: true
          DCTL_FROM: "tfstate://tests/terraform.tfstate"
          DCTL_DRIFTIGNORE: "tests/.driftignore"
          DCTL_FILTER: "Type=='unknown_type'" # Makes driftctl to exit 0 each time
        with:
          version: ${{ matrix.version }}
